# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
      - name: access to secrets
        run: |
          echo "SECRET_TOKEN=$SECRET_TOKEN" >> .env
        env:
          SECRET_TOKEN: ${{secrets.SECRET_TOKEN}}
