name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Set SECRET_TOKEN environment variable
      run: |
        echo "SECRET_TOKEN=$SECRET_TOKEN" >> .env
      env:
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
    
    - name: Check .env file
      run: cat .env
    
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest discover
    - name: Lint code
      run: pylint your_module

